### ISSUE TITLE
Could not find solmet-0.1.jar

### ISSUE THREAD

**Issue by sabreen2020** [chicxurug/SolMet-Solidity-parser#2]
Hello there, 
I am trying to install SolMet 
But, I have this error Error: Unable to access jarfile solmet-0.1.ja

I did this steps to install SolMet 
sudo apt install maven
sudo mvn package 

java -jar solmet-0.1.jar '/home/Users/Desktop/try/contracts/Inbox.sol' 

Can you clarify that for me 

Thanks

**Comment by chicxurug** [comment]
Hey,

By default, the package will be created in the target folder, thus to run 
it, you need to use

java -jar target/solmet-0.1.jar

Let me know if that works.

Peter
