### ISSUE TITLE
Missing required options: outFile, [-inputFile, -basePath]

### ISSUE THREAD

**Issue by saarshah** [chicxurug/SolMet-Solidity-parser#3]
I have adapted following method to use SolMet;
1. Git clone https://github.com/chicxurug/SolMet-Solidity-parser.git
2. Cd SolMet-Solidity-parser
3. mvn package
4. java -jar target\SolMet-1.0-SNAPSHOT.jar D:\MyContract.sol D:\op.txt

then it give following error;
```
Missing required options: outFile, [-inputFile, -basePath]
usage: java -jar SolMet-1.0-SNAPSHOT.jar
 -basePath <path>
 -inputFile <file>
 -outFile <name>     output file
```

**Comment by chicxurug** [comment]
As you can read, you need to specify command line arguments with argument names. So you need to call the following:
java -jar target\SolMet-1.0-SNAPSHOT.jar -inputFile D:\MyContract.sol -outFile D:\op.txt

**Comment by saarshah** [comment]
@chicxurug thanks for your prompt reply and it works for me... I think this step by step detail should also be in your Readme file..
