### ISSUE TITLE
Parameter error

### ISSUE THREAD

**Issue by chengfengyun** [chicxurug/SolMet-Solidity-parser#4]
My **environment** is: 
- system version: Win 10
- java version: "1.8.0_211"
- mvn version: Apache Maven 3.5.4

When I run the following commands in PowerShell, the following error tips will always appear.

**command**: 
`java -jar .\target\SolMet-1.0-SNAPSHOT.jar D:\Project\source_code  .\out.csv `
or
`java -jar .\target\SolMet-1.0-SNAPSHOT.jar D:\Project\source_code test.sol  .\out.csv `

**Error tip**:
Missing required options: outFile, [-inputFile, -basePath]
usage: java -jar SolMet-1.0-SNAPSHOT.jar
 -basePath <path>
 -inputFile <file>
 -outFile <name>     output file

**Comment by chicxurug** [comment]
That is because you need to use keyword arguments like this:
java -jar .\target\SolMet-1.0-SNAPSHOT.jar -basePath D:\Project\source_code -outFile .\out.csv 
OR
java -jar .\target\SolMet-1.0-SNAPSHOT.jar -inputFile D:\Project\source_code\test.sol -outFIle .\out.csv

**Comment by chicxurug** [comment]
Misuse of keyword arguments.
