### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException        

### ISSUE THREAD

**Issue by chengfengyun** [chicxurug/SolMet-Solidity-parser#5]
`java -jar .\target\SolMet-1.0-SNAPSHOT.jar -basePath D:\source_code  -outFile .\out.csv`

When I run the above command, there is a new error message:

Exception in thread "main" java.lang.NullPointerException   at hu.sed.solmet.main.Main.main(Main.java:68)

**Comment by chicxurug** [comment]
And what is the content of the directory `D:\source_code`? It seems like its empty, but it should contain the Solidity files.

**Comment by chicxurug** [comment]
Oh, no, sorry. I remember now. The `basePath` should contain subfolders (I named the subfolders based on the address of the contracts) and each subfolder should contain a sol file, like this:
- source_code
+- sub_folder1
+--- sol_file1.sol
+- sub_folder2
+--- sol_file2.sol

**Comment by chengfengyun** [comment]
Thank you. It works now.
